"""update sales source & product

Revision ID: 091cb4580580
Revises: 2006b018505c
Create Date: 2026-05-25 03:44:42.558541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '091cb4580580'
down_revision: Union[str, Sequence[str], None] = '2006b018505c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. Buat Tabel Master Baru
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id', name='products_pkey'),
    sa.UniqueConstraint('name', name='products_name_key'),
    schema='oltp_sales'
    )
    op.create_table('sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id', name='sources_pkey'),
    sa.UniqueConstraint('name', name='sources_name_key'),
    schema='oltp_sales'
    )

    # 2. Hancurkan tabel Categories beserta SEMUA tali Foreign Key-nya sekaligus!
    op.execute("DROP TABLE IF EXISTS oltp_sales.categories CASCADE")

    # 3. Lepas Unique Constraint lama
    op.drop_constraint('uq_transaction_combination', 'transactions', schema='oltp_sales', type_='unique')

    # 4. Tambahkan kolom baru di tabel Utama dan Staging 
    # (ASUMSI: Tabel transaksimu saat ini sedang KOSONG)
    op.add_column('transactions', sa.Column('source_id', sa.Integer(), nullable=False), schema='oltp_sales')
    op.add_column('transactions', sa.Column('product_id', sa.Integer(), nullable=False), schema='oltp_sales')
    op.add_column('sales_transactions', sa.Column('source_id', sa.Integer(), nullable=False), schema='stg_table')
    op.add_column('sales_transactions', sa.Column('product_id', sa.Integer(), nullable=False), schema='stg_table')

    # 5. Pasang Unique Constraint baru
    op.create_unique_constraint('uq_transaction_combination', 'transactions', ['date', 'source_id', 'product_id', 'grade_id', 'week_id'], schema='oltp_sales')

    # 6. Pasang Foreign Key baru
    op.create_foreign_key('fk_sales_product', 'transactions', 'products', ['product_id'], ['id'], source_schema='oltp_sales', referent_schema='oltp_sales', ondelete='RESTRICT')
    op.create_foreign_key('fk_sales_source', 'transactions', 'sources', ['source_id'], ['id'], source_schema='oltp_sales', referent_schema='oltp_sales', ondelete='RESTRICT')
    op.create_foreign_key('fk_stg_sales_product', 'sales_transactions', 'products', ['product_id'], ['id'], source_schema='stg_table', referent_schema='oltp_sales')
    op.create_foreign_key('fk_stg_sales_source', 'sales_transactions', 'sources', ['source_id'], ['id'], source_schema='stg_table', referent_schema='oltp_sales')

    # 7. Buang kolom lama (category_id)
    op.drop_column('transactions', 'category_id', schema='oltp_sales')
    op.drop_column('sales_transactions', 'category_id', schema='stg_table')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales_transactions', sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=False), schema='stg_table')
    op.drop_constraint('fk_stg_sales_source', 'sales_transactions', schema='stg_table', type_='foreignkey')
    op.drop_constraint('fk_stg_sales_product', 'sales_transactions', schema='stg_table', type_='foreignkey')
    op.create_foreign_key(op.f('fk_stg_sales_category'), 'sales_transactions', 'categories', ['category_id'], ['id'], source_schema='stg_table', referent_schema='oltp_sales')
    op.drop_column('sales_transactions', 'product_id', schema='stg_table')
    op.drop_column('sales_transactions', 'source_id', schema='stg_table')
    op.add_column('transactions', sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=False), schema='oltp_sales')
    op.drop_constraint('fk_sales_source', 'transactions', schema='oltp_sales', type_='foreignkey')
    op.drop_constraint('fk_sales_product', 'transactions', schema='oltp_sales', type_='foreignkey')
    op.create_foreign_key(op.f('fk_sales_category'), 'transactions', 'categories', ['category_id'], ['id'], source_schema='oltp_sales', referent_schema='oltp_sales', ondelete='RESTRICT')
    op.drop_constraint('uq_transaction_combination', 'transactions', schema='oltp_sales', type_='unique')
    op.create_unique_constraint(op.f('uq_transaction_combination'), 'transactions', ['date', 'category_id', 'grade_id', 'week_id'], schema='oltp_sales', postgresql_nulls_not_distinct=False)
    op.drop_column('transactions', 'product_id', schema='oltp_sales')
    op.drop_column('transactions', 'source_id', schema='oltp_sales')
    op.create_table('categories',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('categories_pkey')),
    sa.UniqueConstraint('name', name=op.f('categories_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    schema='oltp_sales'
    )
    op.drop_table('sources', schema='oltp_sales')
    op.drop_table('products', schema='oltp_sales')
    # ### end Alembic commands ###
