"""update status colum in stg table

Revision ID: 2006b018505c
Revises: 2e01b5a3fa74
Create Date: 2026-05-24 05:04:44.523310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2006b018505c'
down_revision: Union[str, Sequence[str], None] = '2e01b5a3fa74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchasing_sheet1_transactions', sa.Column('status', postgresql.ENUM('replace', 'insert', name='status_action_enum', schema='stg_table', create_type=False), nullable=True), schema='stg_table')
    op.add_column('purchasing_sheet2_transactions', sa.Column('status', postgresql.ENUM('replace', 'insert', name='status_action_enum', schema='stg_table', create_type=False), nullable=True), schema='stg_table')
    op.add_column('purchasing_sheet3_transactions', sa.Column('status', postgresql.ENUM('replace', 'insert', name='status_action_enum', schema='stg_table', create_type=False), nullable=True), schema='stg_table')
    op.add_column('sales_transactions', sa.Column('status', postgresql.ENUM('replace', 'insert', name='status_action_enum', schema='stg_table', create_type=False), nullable=True), schema='stg_table')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales_transactions', 'status', schema='stg_table')
    op.drop_column('purchasing_sheet3_transactions', 'status', schema='stg_table')
    op.drop_column('purchasing_sheet2_transactions', 'status', schema='stg_table')
    op.drop_column('purchasing_sheet1_transactions', 'status', schema='stg_table')
    # ### end Alembic commands ###
