"""Initial migration

Revision ID: 560dea5825e9
Revises: 
Create Date: 2026-05-22 13:41:25.010519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '560dea5825e9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('replace', 'insert', name='status_action_enum', schema='stg_table').create(op.get_bind())
    sa.Enum('ACTUAL', 'BUDGET', 'NA', name='actual_budget_enum', schema='oltp_finance').create(op.get_bind())
    op.create_table('account_names',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('account_name', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_finance_account_names'),
    sa.UniqueConstraint('account_name', name='uq_finance_account_names_account_name'),
    schema='oltp_finance'
    )
    op.create_table('categories',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_finance_categories'),
    sa.UniqueConstraint('name', name='uq_finance_categories_name'),
    schema='oltp_finance'
    )
    op.create_table('sheets',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_finance_sheets'),
    sa.UniqueConstraint('name', name='uq_finance_sheets_name'),
    schema='oltp_finance'
    )
    op.create_table('sub_categories',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_finance_sub_categories'),
    sa.UniqueConstraint('name', name='uq_finance_sub_categories_name'),
    schema='oltp_finance'
    )
    op.create_table('sub_sub_categories',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('is_placeholder', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_finance_sub_sub_categories'),
    sa.UniqueConstraint('name', name='uq_finance_sub_sub_categories_name'),
    schema='oltp_finance'
    )
    op.create_table('vw_transaction_rule_lookup',
    sa.Column('rule_id', sa.BigInteger(), nullable=True),
    sa.Column('sheet_name', sa.Text(), nullable=True),
    sa.Column('category_name', sa.Text(), nullable=True),
    sa.Column('sub_category_name', sa.Text(), nullable=True),
    sa.Column('sub_sub_category_name', sa.Text(), nullable=True),
    sa.Column('account_name', sa.Text(), nullable=True),
    sa.Column('actual_budget', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    schema='oltp_finance'
    )
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=True),
    sa.Column('public_id', sa.String(length=22), nullable=True),
    sa.PrimaryKeyConstraint('id', name='departments_pkey'),
    schema='oltp_main'
    )
    op.create_index('ix_departments_public_id', 'departments', ['public_id'], unique=True, schema='oltp_main')
    op.create_index('ix_oltp_main_departments_public_id', 'departments', ['public_id'], unique=True, schema='oltp_main')
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', postgresql.ENUM('STAFF', 'MANAGER', 'DIREKTUR', 'ADMIN', name='role_enum', schema='oltp_main', create_type=False), nullable=True),
    sa.Column('public_id', sa.String(length=22), nullable=True),
    sa.PrimaryKeyConstraint('id', name='roles_pkey'),
    schema='oltp_main'
    )
    op.create_index('ix_oltp_main_roles_public_id', 'roles', ['public_id'], unique=True, schema='oltp_main')
    op.create_index('ix_roles_public_id', 'roles', ['public_id'], unique=True, schema='oltp_main')
    op.create_table('vw_finance_transaction_rule_lookup',
    sa.Column('rule_id', sa.BigInteger(), nullable=True),
    sa.Column('sheet_name', sa.Text(), nullable=True),
    sa.Column('category_name', sa.Text(), nullable=True),
    sa.Column('sub_category_name', sa.Text(), nullable=True),
    sa.Column('sub_sub_category_name', sa.Text(), nullable=True),
    sa.Column('account_name', sa.Text(), nullable=True),
    sa.Column('actual_budget', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    schema='oltp_main'
    )
    op.create_table('delivery_details',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_purchasing_delivery_details'),
    sa.UniqueConstraint('name', name='uq_purchasing_delivery_details_name'),
    schema='oltp_purchasing'
    )
    op.create_table('details',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_purchasing_details'),
    sa.UniqueConstraint('name', name='uq_purchasing_details_name'),
    schema='oltp_purchasing'
    )
    op.create_table('grades',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_purchasing_grades'),
    sa.UniqueConstraint('name', name='uq_purchasing_grades_name'),
    schema='oltp_purchasing'
    )
    op.create_table('origins',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_purchasing_origins'),
    sa.UniqueConstraint('name', name='uq_purchasing_origins_name'),
    schema='oltp_purchasing'
    )
    op.create_table('suppliers',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_purchasing_suppliers'),
    sa.UniqueConstraint('name', name='uq_purchasing_suppliers_name'),
    schema='oltp_purchasing'
    )
    op.create_table('varieties',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_purchasing_varieties'),
    sa.UniqueConstraint('name', name='uq_purchasing_varieties_name'),
    schema='oltp_purchasing'
    )
    op.create_table('vw_sheet2_master',
    sa.Column('master_type', sa.Text(), nullable=True),
    sa.Column('master_id', sa.BigInteger(), nullable=True),
    sa.Column('master_name', sa.Text(), nullable=True),
    schema='oltp_purchasing'
    )
    op.create_table('vw_sheet3_rules',
    sa.Column('rule_id', sa.BigInteger(), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('variety', sa.Text(), nullable=True),
    schema='oltp_purchasing'
    )
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id', name='categories_pkey'),
    sa.UniqueConstraint('name', name='categories_name_key'),
    schema='oltp_sales'
    )
    op.create_table('grades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id', name='grades_pkey'),
    sa.UniqueConstraint('name', name='grades_name_key'),
    schema='oltp_sales'
    )
    op.create_table('vw_all_masters',
    sa.Column('master_type', sa.Text(), nullable=True),
    sa.Column('master_id', sa.Integer(), nullable=True),
    sa.Column('master_name', sa.String(), nullable=True),
    schema='oltp_sales'
    )
    op.create_table('weeks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id', name='weeks_pkey'),
    schema='oltp_sales'
    )
    op.create_table('transaction_rules',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('sheet_id', sa.BigInteger(), nullable=False),
    sa.Column('category_id', sa.BigInteger(), nullable=False),
    sa.Column('sub_category_id', sa.BigInteger(), nullable=False),
    sa.Column('sub_sub_category_id', sa.BigInteger(), nullable=False),
    sa.Column('account_name_id', sa.BigInteger(), nullable=False),
    sa.Column('actual_budget', postgresql.ENUM('ACTUAL', 'BUDGET', 'NA', name='actual_budget_enum', schema='oltp_finance', create_type=False), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_name_id'], ['oltp_finance.account_names.id'], name='fk_finance_transaction_rules_account_name'),
    sa.ForeignKeyConstraint(['category_id'], ['oltp_finance.categories.id'], name='fk_finance_transaction_rules_category'),
    sa.ForeignKeyConstraint(['sheet_id'], ['oltp_finance.sheets.id'], name='fk_finance_transaction_rules_sheet'),
    sa.ForeignKeyConstraint(['sub_category_id'], ['oltp_finance.sub_categories.id'], name='fk_finance_transaction_rules_sub_category'),
    sa.ForeignKeyConstraint(['sub_sub_category_id'], ['oltp_finance.sub_sub_categories.id'], name='fk_finance_transaction_rules_sub_sub_category'),
    sa.PrimaryKeyConstraint('id', name='pk_finance_transaction_rules'),
    sa.UniqueConstraint('sheet_id', 'category_id', 'sub_category_id', 'sub_sub_category_id', 'account_name_id', 'actual_budget', name='uq_finance_transaction_rules_combo'),
    schema='oltp_finance'
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nik', sa.String(length=16), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('public_id', sa.String(length=22), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['oltp_main.departments.id'], name='users_id_dept_fkey'),
    sa.ForeignKeyConstraint(['role_id'], ['oltp_main.roles.id'], name='users_id_roles_fkey'),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    schema='oltp_main'
    )
    op.create_index('ix_oltp_main_users_id_dept', 'users', ['department_id'], unique=False, schema='oltp_main')
    op.create_index('ix_oltp_main_users_id_roles', 'users', ['role_id'], unique=False, schema='oltp_main')
    op.create_index('ix_oltp_main_users_nik_active', 'users', ['nik'], unique=True, schema='oltp_main', postgresql_where='(deleted_at IS NULL)')
    op.create_index('ix_oltp_main_users_public_id', 'users', ['public_id'], unique=True, schema='oltp_main')
    op.create_index('ix_users_public_id', 'users', ['public_id'], unique=True, schema='oltp_main')
    op.create_table('sheet3_transaction_rules',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('variety_id', sa.BigInteger(), nullable=False),
    sa.Column('detail_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['detail_id'], ['oltp_purchasing.details.id'], name='fk_purchasing_sheet3_rules_detail'),
    sa.ForeignKeyConstraint(['variety_id'], ['oltp_purchasing.varieties.id'], name='fk_purchasing_sheet3_rules_variety'),
    sa.PrimaryKeyConstraint('id', name='pk_purchasing_sheet3_transaction_rules'),
    sa.UniqueConstraint('variety_id', 'detail_id', name='uq_purchasing_sheet3_rules_combo'),
    schema='oltp_purchasing'
    )
    op.create_table('history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('time_stamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', postgresql.ENUM('ANALYZING', 'AWAITING_PREVIEW', 'PROCESSING_INSERT', 'PENDING', 'APPROVED', 'REJECTED', 'FAILED', 'CANCELLED', name='status_enum', schema='oltp_main', create_type=False), nullable=False),
    sa.Column('analysis_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('file_name_storage', sa.String(length=255), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('public_id', sa.String(length=22), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['oltp_main.departments.id'], name='history_upload_id_dept_fkey'),
    sa.ForeignKeyConstraint(['role_id'], ['oltp_main.roles.id'], name='history_upload_id_roles_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['oltp_main.users.id'], name='history_upload_id_users_fkey'),
    sa.PrimaryKeyConstraint('id', name='history_upload_pkey'),
    sa.UniqueConstraint('public_id', name='history_public_id_unique'),
    schema='oltp_main'
    )
    op.create_index('ix_history_public_id', 'history', ['public_id'], unique=True, schema='oltp_main')
    op.create_index('ix_history_upload_public_id', 'history', ['public_id'], unique=False, schema='oltp_main')
    op.create_index('ix_oltp_main_history_public_id', 'history', ['public_id'], unique=True, schema='oltp_main')
    op.create_index('ix_oltp_main_history_upload_id_dept', 'history', ['department_id'], unique=False, schema='oltp_main')
    op.create_index('ix_oltp_main_history_upload_id_roles', 'history', ['role_id'], unique=False, schema='oltp_main')
    op.create_index('ix_oltp_main_history_upload_id_users', 'history', ['user_id'], unique=False, schema='oltp_main')
    op.create_table('transactions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('history_id', sa.BigInteger(), nullable=False),
    sa.Column('rule_id', sa.BigInteger(), nullable=False),
    sa.Column('period_month', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=26, scale=6), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['history_id'], ['oltp_main.history.id'], name='fk_oltp_finance_transactions_history'),
    sa.ForeignKeyConstraint(['rule_id'], ['oltp_finance.transaction_rules.id'], name='fk_oltp_finance_transactions_rule'),
    sa.PrimaryKeyConstraint('id', name='pk_oltp_finance_transactions'),
    sa.UniqueConstraint('rule_id', 'period_month', name='uq_oltp_finance_transactions_rule_month'),
    schema='oltp_finance'
    )
    op.create_table('sheet1_transactions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('history_id', sa.Integer(), nullable=False),
    sa.Column('price_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('tex_us_no_1h_cfr_korea_domestic_cost', sa.Integer(), nullable=True),
    sa.Column('lme_usno_1_2_80_20_cfr_turkey_domestic_cost', sa.REAL(), nullable=True),
    sa.Column('local_price_usd', sa.REAL(), nullable=True),
    sa.Column('busheling_contract_usd', sa.Integer(), nullable=True),
    sa.Column('pns_contract_usd', sa.Integer(), nullable=True),
    sa.Column('hms_contract_usd', sa.Integer(), nullable=True),
    sa.Column('shr_contract_usd', sa.Integer(), nullable=True),
    sa.Column('local_price_idr', sa.Integer(), nullable=True),
    sa.Column('usd_rate', sa.REAL(), nullable=True),
    sa.Column('idr_rate', sa.Integer(), nullable=True),
    sa.Column('idr_usd_exchange_rate', sa.Integer(), nullable=True),
    sa.Column('us_no_1h_cfr_korea', sa.Integer(), nullable=True),
    sa.Column('lme_usno_1_2_80_20_cfr_turky', sa.Integer(), nullable=True),
    sa.Column('lme_usno_1_2_80_20_cfr_turkey', sa.REAL(), nullable=True),
    sa.Column('local_premium_idr_per_kg', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['history_id'], ['oltp_main.history.id'], name='fk_purchasing_sheet1_transaction_history'),
    sa.PrimaryKeyConstraint('id', name='pk_purchasing_sheet1_transaction'),
    sa.UniqueConstraint('price_date', name='uq_purchasing_sheet1_transaction_price_date'),
    schema='oltp_purchasing'
    )
    op.create_table('sheet2_transactions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('history_id', sa.BigInteger(), nullable=False),
    sa.Column('variety_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('list_no', sa.Integer(), nullable=True),
    sa.Column('contract_date', sa.Date(), nullable=True),
    sa.Column('supplier_id', sa.BigInteger(), nullable=True),
    sa.Column('origin_id', sa.BigInteger(), nullable=True),
    sa.Column('grade_id', sa.BigInteger(), nullable=True),
    sa.Column('delivery_detail_id', sa.BigInteger(), nullable=True),
    sa.Column('ton', sa.BigInteger(), nullable=True),
    sa.Column('price_usd_per_ton_cif', sa.BigInteger(), nullable=True),
    sa.Column('total_usd', sa.BigInteger(), nullable=True),
    sa.Column('delivery', sa.Date(), nullable=True),
    sa.Column('actual_eta', sa.Date(), nullable=True),
    sa.Column('delivery_remarks', sa.Text(), nullable=True),
    sa.Column('avg_qty', sa.BigInteger(), nullable=True),
    sa.Column('avg_value', sa.BigInteger(), nullable=True),
    sa.Column('avg_price', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['delivery_detail_id'], ['oltp_purchasing.delivery_details.id'], name='fk_purchasing_sheet2_transactions_delivery_detail'),
    sa.ForeignKeyConstraint(['grade_id'], ['oltp_purchasing.grades.id'], name='fk_purchasing_sheet2_transactions_grade'),
    sa.ForeignKeyConstraint(['history_id'], ['oltp_main.history.id'], name='fk_purchasing_sheet2_transactions_history'),
    sa.ForeignKeyConstraint(['origin_id'], ['oltp_purchasing.origins.id'], name='fk_purchasing_sheet2_transactions_origin'),
    sa.ForeignKeyConstraint(['supplier_id'], ['oltp_purchasing.suppliers.id'], name='fk_purchasing_sheet2_transactions_supplier'),
    sa.ForeignKeyConstraint(['variety_id'], ['oltp_purchasing.varieties.id'], name='fk_purchasing_sheet2_transactions_variety'),
    sa.PrimaryKeyConstraint('id', name='pk_purchasing_sheet2_transactions'),
    sa.UniqueConstraint('variety_id', 'list_no', 'contract_date', 'supplier_id', 'grade_id', name='uq_purchasing_sheet2_transactions_business_key'),
    schema='oltp_purchasing'
    )
    op.create_table('sheet3_transactions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('history_id', sa.BigInteger(), nullable=False),
    sa.Column('rule_id', sa.BigInteger(), nullable=False),
    sa.Column('period_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('value', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['history_id'], ['oltp_main.history.id'], name='fk_purchasing_sheet3_transactions_history'),
    sa.ForeignKeyConstraint(['rule_id'], ['oltp_purchasing.sheet3_transaction_rules.id'], name='fk_purchasing_sheet3_transactions_rule'),
    sa.PrimaryKeyConstraint('id', name='pk_purchasing_sheet3_transactions'),
    sa.UniqueConstraint('rule_id', 'period_date', name='uq_purchasing_sheet3_transactions_rule_period'),
    schema='oltp_purchasing'
    )
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('history_id', sa.BigInteger(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('grade_id', sa.Integer(), nullable=False),
    sa.Column('week_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['oltp_sales.categories.id'], name='fk_sales_category', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['grade_id'], ['oltp_sales.grades.id'], name='fk_sales_grade', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['history_id'], ['oltp_main.history.id'], name='fk_sales_history', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['week_id'], ['oltp_sales.weeks.id'], name='fk_sales_week', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name='transactions_pkey'),
    sa.UniqueConstraint('date', 'category_id', 'grade_id', 'week_id', name='uq_transaction_combination'),
    schema='oltp_sales'
    )
    op.create_table('finance_transactions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('history_id', sa.BigInteger(), nullable=False),
    sa.Column('rule_id', sa.BigInteger(), nullable=False),
    sa.Column('period_month', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=26, scale=6), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', postgresql.ENUM('replace', 'insert', name='status_action_enum', schema='stg_table', create_type=False), nullable=True),
    sa.ForeignKeyConstraint(['history_id'], ['oltp_main.history.id'], name='fk_stg_finance_transactions_history', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rule_id'], ['oltp_finance.transaction_rules.id'], name='fk_stg_finance_transactions_rule'),
    sa.PrimaryKeyConstraint('id', name='pk_stg_finance_transactions'),
    schema='stg_table'
    )
    op.create_table('purchasing_sheet1_transactions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('history_id', sa.Integer(), nullable=False),
    sa.Column('price_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('tex_us_no_1h_cfr_korea_domestic_cost', sa.Integer(), nullable=True),
    sa.Column('lme_usno_1_2_80_20_cfr_turkey_domestic_cost', sa.REAL(), nullable=True),
    sa.Column('local_price_usd', sa.REAL(), nullable=True),
    sa.Column('busheling_contract_usd', sa.Integer(), nullable=True),
    sa.Column('pns_contract_usd', sa.Integer(), nullable=True),
    sa.Column('hms_contract_usd', sa.Integer(), nullable=True),
    sa.Column('shr_contract_usd', sa.Integer(), nullable=True),
    sa.Column('local_price_idr', sa.Integer(), nullable=True),
    sa.Column('usd_rate', sa.REAL(), nullable=True),
    sa.Column('idr_rate', sa.Integer(), nullable=True),
    sa.Column('idr_usd_exchange_rate', sa.Integer(), nullable=True),
    sa.Column('us_no_1h_cfr_korea', sa.Integer(), nullable=True),
    sa.Column('lme_usno_1_2_80_20_cfr_turky', sa.Integer(), nullable=True),
    sa.Column('lme_usno_1_2_80_20_cfr_turkey', sa.REAL(), nullable=True),
    sa.Column('local_premium_idr_per_kg', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['history_id'], ['oltp_main.history.id'], name='fk_purchasing_sheet1_transaction_history'),
    sa.PrimaryKeyConstraint('id', name='pk_purchasing_sheet1_transaction'),
    schema='stg_table'
    )
    op.create_table('purchasing_sheet2_transactions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('history_id', sa.BigInteger(), nullable=False),
    sa.Column('variety_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('list_no', sa.Integer(), nullable=True),
    sa.Column('contract_date', sa.Date(), nullable=True),
    sa.Column('supplier_id', sa.BigInteger(), nullable=True),
    sa.Column('origin_id', sa.BigInteger(), nullable=True),
    sa.Column('grade_id', sa.BigInteger(), nullable=True),
    sa.Column('delivery_detail_id', sa.BigInteger(), nullable=True),
    sa.Column('ton', sa.BigInteger(), nullable=True),
    sa.Column('price_usd_per_ton_cif', sa.BigInteger(), nullable=True),
    sa.Column('total_usd', sa.BigInteger(), nullable=True),
    sa.Column('delivery', sa.Date(), nullable=True),
    sa.Column('actual_eta', sa.Date(), nullable=True),
    sa.Column('delivery_remarks', sa.Text(), nullable=True),
    sa.Column('avg_qty', sa.BigInteger(), nullable=True),
    sa.Column('avg_value', sa.BigInteger(), nullable=True),
    sa.Column('avg_price', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['delivery_detail_id'], ['oltp_purchasing.delivery_details.id'], name='fk_stg_purchasing_sheet2_transactions_delivery_detail'),
    sa.ForeignKeyConstraint(['grade_id'], ['oltp_purchasing.grades.id'], name='fk_stg_purchasing_sheet2_transactions_grade'),
    sa.ForeignKeyConstraint(['history_id'], ['oltp_main.history.id'], name='fk_stg_purchasing_sheet2_transactions_history', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['origin_id'], ['oltp_purchasing.origins.id'], name='fk_stg_purchasing_sheet2_transactions_origin'),
    sa.ForeignKeyConstraint(['supplier_id'], ['oltp_purchasing.suppliers.id'], name='fk_stg_purchasing_sheet2_transactions_supplier'),
    sa.ForeignKeyConstraint(['variety_id'], ['oltp_purchasing.varieties.id'], name='fk_stg_purchasing_sheet2_transactions_variety'),
    sa.PrimaryKeyConstraint('id', name='pk_stg_purchasing_sheet2_transactions'),
    schema='stg_table'
    )
    op.create_table('purchasing_sheet3_transactions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('history_id', sa.BigInteger(), nullable=False),
    sa.Column('rule_id', sa.BigInteger(), nullable=False),
    sa.Column('period_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('value', sa.Numeric(precision=26, scale=6), nullable=True),
    sa.ForeignKeyConstraint(['history_id'], ['oltp_main.history.id'], name='fk_stg_purchasing_sheet3_transactions_history', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rule_id'], ['oltp_purchasing.sheet3_transaction_rules.id'], name='fk_stg_purchasing_sheet3_transactions_rule'),
    sa.PrimaryKeyConstraint('id', name='pk_stg_purchasing_sheet3_transactions'),
    schema='stg_table'
    )
    op.create_table('sales_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('history_id', sa.BigInteger(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('grade_id', sa.Integer(), nullable=False),
    sa.Column('week_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['history_id'], ['oltp_main.history.id'], name='fk_sales_history', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name='sales_transactions_pkey'),
    schema='stg_table'
    )
    sa.Enum('ACTUAL', 'BUDGET', 'NA', name='actual_budget_enum', schema='oltp_main').drop(op.get_bind())
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('ACTUAL', 'BUDGET', 'NA', name='actual_budget_enum', schema='oltp_main').create(op.get_bind())
    op.drop_table('sales_transactions', schema='stg_table')
    op.drop_table('purchasing_sheet3_transactions', schema='stg_table')
    op.drop_table('purchasing_sheet2_transactions', schema='stg_table')
    op.drop_table('purchasing_sheet1_transactions', schema='stg_table')
    op.drop_table('finance_transactions', schema='stg_table')
    op.drop_table('transactions', schema='oltp_sales')
    op.drop_table('sheet3_transactions', schema='oltp_purchasing')
    op.drop_table('sheet2_transactions', schema='oltp_purchasing')
    op.drop_table('sheet1_transactions', schema='oltp_purchasing')
    op.drop_table('transactions', schema='oltp_finance')
    op.drop_index('ix_oltp_main_history_upload_id_users', table_name='history', schema='oltp_main')
    op.drop_index('ix_oltp_main_history_upload_id_roles', table_name='history', schema='oltp_main')
    op.drop_index('ix_oltp_main_history_upload_id_dept', table_name='history', schema='oltp_main')
    op.drop_index('ix_oltp_main_history_public_id', table_name='history', schema='oltp_main')
    op.drop_index('ix_history_upload_public_id', table_name='history', schema='oltp_main')
    op.drop_index('ix_history_public_id', table_name='history', schema='oltp_main')
    op.drop_table('history', schema='oltp_main')
    op.drop_table('sheet3_transaction_rules', schema='oltp_purchasing')
    op.drop_index('ix_users_public_id', table_name='users', schema='oltp_main')
    op.drop_index('ix_oltp_main_users_public_id', table_name='users', schema='oltp_main')
    op.drop_index('ix_oltp_main_users_nik_active', table_name='users', schema='oltp_main', postgresql_where='(deleted_at IS NULL)')
    op.drop_index('ix_oltp_main_users_id_roles', table_name='users', schema='oltp_main')
    op.drop_index('ix_oltp_main_users_id_dept', table_name='users', schema='oltp_main')
    op.drop_table('users', schema='oltp_main')
    op.drop_table('transaction_rules', schema='oltp_finance')
    op.drop_table('weeks', schema='oltp_sales')
    op.drop_table('vw_all_masters', schema='oltp_sales')
    op.drop_table('grades', schema='oltp_sales')
    op.drop_table('categories', schema='oltp_sales')
    op.drop_table('vw_sheet3_rules', schema='oltp_purchasing')
    op.drop_table('vw_sheet2_master', schema='oltp_purchasing')
    op.drop_table('varieties', schema='oltp_purchasing')
    op.drop_table('suppliers', schema='oltp_purchasing')
    op.drop_table('origins', schema='oltp_purchasing')
    op.drop_table('grades', schema='oltp_purchasing')
    op.drop_table('details', schema='oltp_purchasing')
    op.drop_table('delivery_details', schema='oltp_purchasing')
    op.drop_table('vw_finance_transaction_rule_lookup', schema='oltp_main')
    op.drop_index('ix_roles_public_id', table_name='roles', schema='oltp_main')
    op.drop_index('ix_oltp_main_roles_public_id', table_name='roles', schema='oltp_main')
    op.drop_table('roles', schema='oltp_main')
    op.drop_index('ix_oltp_main_departments_public_id', table_name='departments', schema='oltp_main')
    op.drop_index('ix_departments_public_id', table_name='departments', schema='oltp_main')
    op.drop_table('departments', schema='oltp_main')
    op.drop_table('vw_transaction_rule_lookup', schema='oltp_finance')
    op.drop_table('sub_sub_categories', schema='oltp_finance')
    op.drop_table('sub_categories', schema='oltp_finance')
    op.drop_table('sheets', schema='oltp_finance')
    op.drop_table('categories', schema='oltp_finance')
    op.drop_table('account_names', schema='oltp_finance')
    sa.Enum('ACTUAL', 'BUDGET', 'NA', name='actual_budget_enum', schema='oltp_finance').drop(op.get_bind())
    sa.Enum('replace', 'insert', name='status_action_enum', schema='stg_table').drop(op.get_bind())
    # ### end Alembic commands ###
