"""rubah tipe data float di sheet 2

Revision ID: 68771fea8ba3
Revises: 091cb4580580
Create Date: 2026-05-26 04:52:15.964974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68771fea8ba3'
down_revision: Union[str, Sequence[str], None] = '091cb4580580'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sheet2_transactions', 'avg_qty',
               existing_type=sa.BIGINT(),
               type_=sa.Float(),
               existing_nullable=True,
               schema='oltp_purchasing')
    op.alter_column('sheet2_transactions', 'avg_value',
               existing_type=sa.BIGINT(),
               type_=sa.Numeric(precision=15, scale=2),
               existing_nullable=True,
               schema='oltp_purchasing')
    op.alter_column('sheet2_transactions', 'avg_price',
               existing_type=sa.BIGINT(),
               type_=sa.Numeric(precision=15, scale=2),
               existing_nullable=True,
               schema='oltp_purchasing')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sheet2_transactions', 'avg_price',
               existing_type=sa.Numeric(precision=15, scale=2),
               type_=sa.BIGINT(),
               existing_nullable=True,
               schema='oltp_purchasing')
    op.alter_column('sheet2_transactions', 'avg_value',
               existing_type=sa.Numeric(precision=15, scale=2),
               type_=sa.BIGINT(),
               existing_nullable=True,
               schema='oltp_purchasing')
    op.alter_column('sheet2_transactions', 'avg_qty',
               existing_type=sa.Float(),
               type_=sa.BIGINT(),
               existing_nullable=True,
               schema='oltp_purchasing')
    # ### end Alembic commands ###
