"""rubah tipe data float ke sheet 3 value nya

Revision ID: 83ff707d2377
Revises: 68771fea8ba3
Create Date: 2026-05-26 05:10:31.117466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83ff707d2377'
down_revision: Union[str, Sequence[str], None] = '68771fea8ba3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sheet3_transactions', 'value',
               existing_type=sa.BIGINT(),
               type_=sa.Numeric(precision=15, scale=2),
               existing_nullable=True,
               schema='oltp_purchasing')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sheet3_transactions', 'value',
               existing_type=sa.Numeric(precision=15, scale=2),
               type_=sa.BIGINT(),
               existing_nullable=True,
               schema='oltp_purchasing')
    # ### end Alembic commands ###
