"""rubah tipe data float ke sheet 2 3 stg table value nya

Revision ID: d4038654291e
Revises: 83ff707d2377
Create Date: 2026-05-26 05:35:44.848490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4038654291e'
down_revision: Union[str, Sequence[str], None] = '83ff707d2377'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sheet2_transactions', 'avg_value',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               type_=sa.Numeric(precision=26, scale=6),
               existing_nullable=True,
               schema='oltp_purchasing')
    op.alter_column('sheet2_transactions', 'avg_price',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               type_=sa.Numeric(precision=26, scale=6),
               existing_nullable=True,
               schema='oltp_purchasing')
    op.alter_column('sheet3_transactions', 'value',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               type_=sa.Numeric(precision=26, scale=6),
               existing_nullable=True,
               schema='oltp_purchasing')
    op.alter_column('purchasing_sheet2_transactions', 'avg_qty',
               existing_type=sa.BIGINT(),
               type_=sa.Float(),
               existing_nullable=True,
               schema='stg_table')
    op.alter_column('purchasing_sheet2_transactions', 'avg_value',
               existing_type=sa.BIGINT(),
               type_=sa.Numeric(precision=26, scale=6),
               existing_nullable=True,
               schema='stg_table')
    op.alter_column('purchasing_sheet2_transactions', 'avg_price',
               existing_type=sa.BIGINT(),
               type_=sa.Numeric(precision=26, scale=6),
               existing_nullable=True,
               schema='stg_table')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('purchasing_sheet2_transactions', 'avg_price',
               existing_type=sa.Numeric(precision=26, scale=6),
               type_=sa.BIGINT(),
               existing_nullable=True,
               schema='stg_table')
    op.alter_column('purchasing_sheet2_transactions', 'avg_value',
               existing_type=sa.Numeric(precision=26, scale=6),
               type_=sa.BIGINT(),
               existing_nullable=True,
               schema='stg_table')
    op.alter_column('purchasing_sheet2_transactions', 'avg_qty',
               existing_type=sa.Float(),
               type_=sa.BIGINT(),
               existing_nullable=True,
               schema='stg_table')
    op.alter_column('sheet3_transactions', 'value',
               existing_type=sa.Numeric(precision=26, scale=6),
               type_=sa.NUMERIC(precision=15, scale=2),
               existing_nullable=True,
               schema='oltp_purchasing')
    op.alter_column('sheet2_transactions', 'avg_price',
               existing_type=sa.Numeric(precision=26, scale=6),
               type_=sa.NUMERIC(precision=15, scale=2),
               existing_nullable=True,
               schema='oltp_purchasing')
    op.alter_column('sheet2_transactions', 'avg_value',
               existing_type=sa.Numeric(precision=26, scale=6),
               type_=sa.NUMERIC(precision=15, scale=2),
               existing_nullable=True,
               schema='oltp_purchasing')
    # ### end Alembic commands ###
