"""Fix Sales Relation

Revision ID: e9fb32fcd721
Revises: 364c53b666a3
Create Date: 2026-05-23 13:52:34.219271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9fb32fcd721'
down_revision: Union[str, Sequence[str], None] = '364c53b666a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('fk_stg_sales_week', 'sales_transactions', 'weeks', ['week_id'], ['id'], source_schema='stg_table', referent_schema='oltp_sales')
    op.create_foreign_key('fk_stg_sales_grade', 'sales_transactions', 'grades', ['grade_id'], ['id'], source_schema='stg_table', referent_schema='oltp_sales')
    op.create_foreign_key('fk_stg_sales_category', 'sales_transactions', 'categories', ['category_id'], ['id'], source_schema='stg_table', referent_schema='oltp_sales')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_stg_sales_category', 'sales_transactions', schema='stg_table', type_='foreignkey')
    op.drop_constraint('fk_stg_sales_grade', 'sales_transactions', schema='stg_table', type_='foreignkey')
    op.drop_constraint('fk_stg_sales_week', 'sales_transactions', schema='stg_table', type_='foreignkey')
    # ### end Alembic commands ###
